
NOYAUDIR = ..

CC = cc
CFLAGS = -W -Wall -g -I$(NOYAUDIR)/include
LDFLAGS = -g -L$(NOYAUDIR)/lib
LDLIBS = -lnoyau

TEST = exo0 exo1 exo2 exo3 exo4 exo5 exam2021 exam2017 

all : $(TEST)

clean :
	rm -f *.o
	rm -f $(TEST)
